name: Deploy DEV (Cloud Run)
on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE_NAME: sferis-mvp-dev
      IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sferis-reg/sferis-mvp-dev:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & Push (Cloud Build → Artifact Registry)
        run: |
          gcloud builds submit --tag $IMAGE

      - name: Deploy to Cloud Run (DEV)
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars=GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars=GCS_BUCKET=${{ secrets.GCS_BUCKET }} \
            --set-env-vars=NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            --set-env-vars=SUBSIDY_RULES_VERSION=2025.2 \
            --set-env-vars=PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium \
            --set-env-vars=MAKE_WEBHOOK_URL=${{ secrets.MAKE_WEBHOOK_URL }} \
            --set-env-vars=GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --set-env-vars=GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --max-instances=3
